apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
# 1. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: default
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  # SQLite 不支持多进程同时写，必须用 Recreate 策略防止多 Pod 冲突
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      # 建议放在比较稳定的节点 (比如有公网 IP 的 server 节点)
      nodeSelector:
        kubernetes.io/hostname: ccs

      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: web
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
          volumeMounts:
            - name: data
              mountPath: /app/data

      volumes:
        - name: data
          hostPath:
            # ⚠️ 请确保 ccs 节点上存在此目录，或有权限创建
            path: /opt/k3s-data/uptime-kuma
            type: DirectoryOrCreate

---
# 2. Service
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-svc
  namespace: default
spec:
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP

---
# 3. Ingress (通过域名访问面板)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-ingress
  namespace: default
spec:
  tls:
    - hosts:
        - uptime.groovydeng.eu.org
      secretName: cf-tls

  rules:
    - host: uptime.groovydeng.eu.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-svc
                port:
                  number: 80