apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-new          
spec:
  capacity:
    storage: 10Gi              
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path  
  local:
    path: /opt/k3s-data/grafana 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ccs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc         
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: grafana-pv-new