apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-ix
  namespace: default
  labels:
    app: cloudflared
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      hostNetwork: true
      dnsPolicy: Default

      nodeSelector:
        kubernetes.io/hostname: ix-20

      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          imagePullPolicy: IfNotPresent
          args:
            - "tunnel"
            - "--no-autoupdate"
            - "run"
            - "--token"
            - "REMOVED"