apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartdns
  labels:
    app: dns
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dns
  template:
    metadata:
      labels:
        app: dns
    spec:
      hostNetwork: true
      dnsPolicy: Default
      affinity:
        # ① 只允许调度到 role=rear or mid 的 node
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - rear
                - mid

        # ② 同一 node 上不允许有第二个 dns
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: dns
            topologyKey: kubernetes.io/hostname

      containers: 
      - name: smartdns
        image: pymumu/smartdns:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Asia/Shanghai"
        volumeMounts:
        - name: config-vol
          mountPath: /etc/smartdns
          
      volumes:
      - name: config-vol
        secret:
          secretName: smartdns-config
