# -------------------
# 1. Vaultwarden 部分
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      # [关键] 强制让 Pod 跑在 Hosteons 机器上，这样才能读到原有的数据
      nodeSelector:
        kubernetes.io/hostname: hosteons # 请确认 kubectl get nodes 显示的名字是这个
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        ports:
        - containerPort: 80
        env:
        - name: SIGNUPS_ALLOWED
          value: "false"
        volumeMounts:
        - name: data-vol
          mountPath: /data
      volumes:
      - name: data-vol
        hostPath:
          # [必须修改] 这里填你在第一步获取的 Hosteons 上的绝对路径
          path: /opt/k3s-data/vaultwarden
          type: Directory

---
# 定义一个 Service，让 Cloudflared 能找到 Vaultwarden
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc # [记注这个名字]
spec:
  selector:
    app: vaultwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# -------------------
# 2. Cloudflared 部分
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1 # Tunnel 只需要一个副本
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      # Tunnel 其实跑在哪个节点都行，但为了管理方便，也可以让它跑在 Hosteons
      # nodeSelector:
      #   kubernetes.io/hostname: hosteons
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: vw-tunnel-secret
              key: TUNNEL_TOKEN 