# -------------------
# 1. Vaultwarden Deployment 
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      nodeSelector:
        kubernetes.io/hostname: hosteons
      containers:
      - name: vaultwarden
        image: docker.io/vaultwarden/server@sha256:3afff94efefc5a4bb89af2fb86f3ac27dff197089e8749ef3c903ed781debd78
        ports:
        - containerPort: 80
        env:
        - name: SIGNUPS_ALLOWED
          value: "false"
        # 建议开启 WebSocket 支持（对于手机端同步很重要）
        - name: WEBSOCKET_ENABLED
          value: "true" 
        volumeMounts:
        - name: data-vol
          mountPath: /data
      volumes:
      - name: data-vol
        hostPath:
          path: /opt/k3s-data/vaultwarden
          type: Directory

---
# -------------------
# 2. Service (保持不变)
# -------------------
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
spec:
  selector:
    app: vaultwarden
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
# -------------------
# 3. Ingress (新增部分)
# -------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden-ingress
spec:
  tls:
    - hosts:
        - value.groovydeng.eu.org
      # 复用你现有的泛域名证书 Secret
      secretName: cf-tls

  rules:
  # !!! 请务必修改这里为你的真实域名 !!!
  - host: value.groovydeng.eu.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaultwarden-svc
            port:
              number: 80