apiVersion: apps/v1
kind: Deployment
metadata:
  name: sing-box-ix
  labels:
    app: sing-box
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sing-box
  template:
    metadata:
      labels:
        app: sing-box
    spec:
      nodeSelector:
        kubernetes.io/hostname: ix-20
      hostNetwork: true
      dnsPolicy: Default

      containers:
      - name: sing-box
        image: ghcr.io/sagernet/sing-box:latest
        imagePullPolicy: Always
        
        # 对应 command: -C /etc/sing-box/ run
        args:
        - "-C"
        - "/etc/sing-box/"
        - "run"
        
        env:
        - name: TZ
          value: "Asia/Shanghai"
        
        # 对应 volumes
        volumeMounts:
        - name: config-vol
          mountPath: /etc/sing-box
        
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -ec
              - |
                export http_proxy="http://127.0.0.1:2000"
                export https_proxy="http://127.0.0.1:2000"
                wget -q -T 10 -O /dev/null http://clients3.google.com/generate_204
          periodSeconds: 120
          timeoutSeconds: 15
          failureThreshold: 2
          
      volumes:
      - name: config-vol
        secret:
          # 注意：这里的名字要和 kustomization.yaml 里的 secretGenerator 名字一致
          secretName: sing-box-config-ix
