# -------------------
# 1. Nginx 配置文件 (ConfigMap)
# -------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        
        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            server_name groovydeng.eu.org blog.groovydeng.eu.org;;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            location /6d9d6/f3b3a3e4b7e8ec1Nbc81JBl20Yc4NsKkN/ {
                alias /etc/nginx/fs/;
                autoindex on;
                autoindex_exact_size off;
                autoindex_localtime on;
                charset utf-8;
            }
        }
    }

---
# -------------------
# 2. Deployment
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-host
  labels:
    app: nginx-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-host
  template:
    metadata:
      labels:
        app: nginx-host
    spec:
      nodeSelector:
        kubernetes.io/hostname: hosteons
      
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        
        ports:
        - containerPort: 80
          name: http
        
        volumeMounts:
        - name: config-main
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
          
        - name: data-fs
          mountPath: /etc/nginx/fs
          readOnly: true
          
        - name: html-public
          mountPath: /usr/share/nginx/html
          readOnly: true
          
        # [已删除] 日志挂载已移除，现在日志会直接输出到 kubectl logs

      volumes:
      - name: config-main
        configMap:
          name: nginx-config
      
      - name: data-fs
        hostPath:
          path: /opt/k3s-data/nginx-compose/fs
          type: DirectoryOrCreate
          
      - name: html-public
        hostPath:
          path: /opt/k3s-data/nginx-compose/public
          type: DirectoryOrCreate
          
      # [已删除] 宿主机的日志目录挂载已移除

---
# -------------------
# 3. Service
# -------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-host
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
# -------------------
# 4. Ingress
# -------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  tls:
  - hosts:
    - groovydeng.eu.org
    secretName: cf-tls

  rules:
  - host: groovydeng.eu.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
 # [新增] 规则 2: 子域名也转发给同一个 Nginx
  - host: blog.groovydeng.eu.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80