---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugo-public
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  # 如果你 k3s 默认就是 local-path，可以不写；写上更明确
  storageClassName: local-path

---  
apiVersion: v1
kind: Pod
metadata:
  name: hugo-build
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: hosteons  # 指定在 hosteons 节点上运行 
  volumes:
    - name: workspace
      emptyDir: {}
    - name: public
      persistentVolumeClaim:
        claimName: hugo-public

  initContainers:
    - name: git-clone
      image: alpine/git:2.47.2
      env:
        - name: REPO_URL
          value: "https://github.com/dyq94310/hugo-me.git" # 改
        - name: BRANCH
          value: "main" # 改
      command: ["/bin/sh","-lc"]
      args:
        - |
          git clone --depth=1 --branch "$BRANCH" "$REPO_URL" /workspace
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  containers:
    - name: hugo
      image: hugomods/hugo:0.148.1
      env:
      - name: workingDir
        value: "workspace/site"
      workingDir: /workspace/site     # 关键：对齐你原来的 ./site
      command: ["/bin/sh","-lc"]
      args:
        - |
          rm -rf /public/*
          hugo --minify --destination /public
      volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: public
          mountPath: /public
