apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hugo-public
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hugo-build
spec:
  backoffLimit: 0               # 失败不重试（你要重试就改成 1/2/3）
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 10 # 可选：完成后 1 小时自动清理 Job（k3s一般可用）
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: hosteons

      volumes:
        - name: workspace
          emptyDir: {}
        - name: public
          persistentVolumeClaim:
            claimName: hugo-public

      initContainers:
        - name: git-clone
          image: alpine/git:2.47.2
          env:
            - name: REPO_URL
              value: "https://github.com/dyq94310/hugo-me.git"
            - name: BRANCH
              value: "main"
          command: ["/bin/sh","-lc"]
          args:
            - |
              git clone --depth=1 --branch "$BRANCH" "$REPO_URL" /workspace
          volumeMounts:
            - name: workspace
              mountPath: /workspace

      containers:
        - name: hugo
          image: hugomods/hugo:0.148.1
          env:
          - name: workingDir
            value: "workspace/site"
          workingDir: /workspace/site
          command: ["/bin/sh","-lc"]
          args:
            - |
              rm -rf /public/*
              hugo --minify --destination /public
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: public
              mountPath: /public
