---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nodepass-secret
  namespace: default
spec:
  encryptedData:
    DASH_TUNNEL_TOKEN: AgCTBbRhcD4vkUwtAzNSWW7XtrUDXZJTrtjjdLRK2uVI21e1KwSo8U/+fZEx9B5EIuOH3p/8Wq+heRNDZJpIvfEmT5uJPX+9H/W0OqEHIGhdjDnSxAKialCvhdhUcxcJet5W8W3jbdz2xY8yA4xaT0KjOa5arDQRntV09+If4J6A7hIWhG29srKaLPdJcibqLBFaV9Ijwf0ZsO9lRU8GmLn/iDXkc2/PWNeXbw/PYZO/oQV8SKzkSUs5Jwi5UO1BCq1zbcI0xL3zpViXg+iYv+pQhSRzsOaET6+oSZCWjM79LnKPu6DQudc2z0fwXmHgo3Y+ORLsLHAfmmC+sQgOku2IzaeUxZ8/UwdQ2vr4oMophKaCgHr1l6uSPmghqvOZtdE5zIjLVhzXFjPthMLKrvfGl1aQz5DkfIKVj1D7zCAb+jJ20p0vbkLKt97vBBZlomffQ/Kt6sf59Iq7oUc5HdkruO8DArVKOXwCH+fdWPh4bFJKFTrKu2wzu+g+OLR3D7pBxt6qS0ZaRelCr/UpEu4DuA81xx7E8UDl+sQ/kP6SjIVehKg9O/tSQ3uneVGMNbxvG3LdelwtOMiA902jSMUaM632d96/erUdpzFP4sdDLPnTzkxIFG64RE8ESg2vJ8W8U373lFaxWDl5RFeR20Tac70a4EA8VHvAmadexY2h6reoM9ilElXxjMF+/dpT6CANVRpsW7D2GwKrzav091S/o1qNL2oy7X9xAVW1qqZlLzMmjxJlRBhulSq+Fq+HGWweMIuD526VR8aMI5OxCJ4GxcBFn+rHqjA4dNed6pcFLixhNOqUu/N0Dvl4Xe4Vuwqo2N+6LGwGCzpsZUvFUCbf7JcNxWPSgDNs9JwTwbChHg1DNQ+M4aeJBm7tneb4Ok7e2AsJHCpoDCMaKIbgKTLrO5ynqcaKi8E73g5zq0EXbpHDNbi7aMA8
  template:
    metadata:
      name: nodepass-secret
      namespace: default
    type: Opaque
