# -------------------
# 1. Sing-box 应用 (核心代理)
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sing-box-cc
  labels:
    app: sing-box-cc
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sing-box
  template:
    metadata:
      labels:
        app: sing-box
    spec:
      # [策略] 钉在 tokyo 节点 (为了读取本地配置)
      nodeSelector:
        kubernetes.io/hostname: tokyo
      hostNetwork: true
      dnsPolicy: Default

      containers:
      - name: sing-box
        image: ghcr.io/sagernet/sing-box:v1.12.13
        imagePullPolicy: IfNotPresent
        # 对应 command: -C /etc/sing-box/ run
        args:
        - "-C"
        - "/etc/sing-box/"
        - "run"
        env:
        - name: TZ
          value: "Asia/Shanghai"
        
        # 9999 是 Cloudflare vless 端口
        ports:
        - containerPort: 9999
          name: cf-api

        volumeMounts:
        - name: config-vol
          mountPath: /etc/sing-box
      
      volumes:
      - name: config-vol
        secret:
          # 注意：这里的名字要和 kustomization.yaml 里的 secretGenerator 名字一致
          secretName: sing-box-config-cc

---
# 2. Service: 连接 Ingress 和 Pod
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: sing-box-cc-svc
  namespace: default
spec:
  selector:
    app: sing-box-cc
  ports:
    - protocol: TCP
      name: web
      port: 80       # Service 暴露给 Ingress 的端口
      targetPort: 9999 # Pod 实际监听的端口
  # 即使是 hostNetwork 的 Pod，ClusterIP Service 依然能通过 Label 找到它
  type: ClusterIP

---
# ==========================================
# 3. Ingress: 管理面板的域名入口 (HTTPS)
# ==========================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sing-box-cc-ingress
  namespace: default
  # 保持简洁，不要多余的 annotations
spec:
  tls:
    - hosts:
        - vless.groovydeng.eu.org
      # 复用你现有的泛域名证书 Secret
      secretName: cf-tls

  rules:
    - host: vless.groovydeng.eu.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sing-box-cc-svc 
                port:
                  number: 80
