# ===========================
# 1. 核心权限 (Demo 中缺失的部分)
# ===========================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: goldpinger
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goldpinger
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: goldpinger
subjects:
  - kind: ServiceAccount
    name: goldpinger
    namespace: default
roleRef:
  kind: ClusterRole
  name: goldpinger
  apiGroup: rbac.authorization.k8s.io

---
# ===========================
# 2. DaemonSet (应用本体)
# ===========================
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goldpinger
  namespace: default
  labels:
    app: goldpinger
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: goldpinger
  template:
    metadata:
      labels:
        app: goldpinger
    spec:
      serviceAccountName: goldpinger
      # 容忍所有污点，确保 Master 节点也被监控
      tolerations:
        - operator: Exists
      containers:
        - name: goldpinger
          # 使用较新版本，v3.0.0 可能在 K8s 1.25+ 上有问题
          image: "docker.io/bloomberg/goldpinger:3.10.2"
          env:
            - name:   
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
            # 让图表显示真实的节点名称 (rich, ix-20 等)
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # 使用 Pod IP 进行互相 Ping (测试 Tailscale 隧道内的通断)
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 80Mi
            requests:
              memory: 40Mi

---
# ===========================
# 3. Service (集群内路由)
# ===========================
apiVersion: v1
kind: Service
metadata:
  name: goldpinger
  namespace: default
spec:
  # 改回 ClusterIP，配合 Ingress 使用
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: goldpinger

---
# ===========================
# 4. Ingress (域名访问)
# ===========================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goldpinger-ingress
  namespace: default
spec:
  tls:
    - hosts:
        - net.groovydeng.eu.org
      secretName: cf-tls
  rules:
    - host: net.groovydeng.eu.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: goldpinger
                port:
                  number: 80