apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: rustfs
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      nodeSelector:
        kubernetes.io/hostname: ccs 
      containers:
      - name: rustfs
        image: rustfs/rustfs:1.0.0-alpha.81 
        env:
        - name: RUSTFS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-secret-config
              key: RUSTFS_ACCESS_KEY

        - name: RUSTFS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rustfs-secret-config
              key: RUSTFS_SECRET_KEY
              
        - name: RUSTFS_CONSOLE_ENABLE
          value: "true"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        resources:
          limits:
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        hostPath:
          path: /opt/k3s-data/rustfs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: rustfs-svc
  namespace: rustfs
spec:
  selector:
    app: rustfs
  ports:
    - name: api
      port: 9000
    - name: console
      port: 9001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-console-ingress
  namespace: rustfs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - rustfs.groovydeng.eu.org # 保持一致
      secretName: cf-tls
  rules:
  - host: rustfs.groovydeng.eu.org # 保持一致
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rustfs-svc
            port:
              number: 9001